version: "3.7"

services:
  web:
    container_name: vuetic-web
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ../components:/usr/src/app/node_modules/@vuetic/components
      - ../models:/usr/src/app/node_modules/@vuetic/models
    ports:
      - 8080:8080
      - 9228:9228
    command: npm run serve
    env_file:
      - .env
    networks:
      - vuetic-net
networks:
  vuetic-net:
